// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/email-bold/BookingConfirmed.tsx": () => import("../components/mockups/email-bold/BookingConfirmed.tsx"),
  "./components/mockups/email-bold/BookingConfirmedMobile.tsx": () => import("../components/mockups/email-bold/BookingConfirmedMobile.tsx"),
  "./components/mockups/email-bold/PaymentVerified.tsx": () => import("../components/mockups/email-bold/PaymentVerified.tsx"),
  "./components/mockups/email-bold/Welcome.tsx": () => import("../components/mockups/email-bold/Welcome.tsx"),
  "./components/mockups/email-editorial/BookingConfirmed.tsx": () => import("../components/mockups/email-editorial/BookingConfirmed.tsx"),
  "./components/mockups/email-editorial/BookingConfirmedMobile.tsx": () => import("../components/mockups/email-editorial/BookingConfirmedMobile.tsx"),
  "./components/mockups/email-editorial/PaymentVerified.tsx": () => import("../components/mockups/email-editorial/PaymentVerified.tsx"),
  "./components/mockups/email-editorial/Welcome.tsx": () => import("../components/mockups/email-editorial/Welcome.tsx"),
  "./components/mockups/email-minimal/BookingConfirmed.tsx": () => import("../components/mockups/email-minimal/BookingConfirmed.tsx"),
  "./components/mockups/email-minimal/BookingConfirmedMobile.tsx": () => import("../components/mockups/email-minimal/BookingConfirmedMobile.tsx"),
  "./components/mockups/email-minimal/PaymentVerified.tsx": () => import("../components/mockups/email-minimal/PaymentVerified.tsx"),
  "./components/mockups/email-minimal/Welcome.tsx": () => import("../components/mockups/email-minimal/Welcome.tsx"),
  "./components/mockups/riplek-home/IntentionLed.tsx": () => import("../components/mockups/riplek-home/IntentionLed.tsx"),
  "./components/mockups/riplek-home/JourneyCompanion.tsx": () => import("../components/mockups/riplek-home/JourneyCompanion.tsx"),
  "./components/mockups/riplek-home/LivePulse.tsx": () => import("../components/mockups/riplek-home/LivePulse.tsx")
};
